name:                ses-haskell
version:             0.1.0.0
github:              "nbrandaleone"
license:             BSD3
author:              "Nick Brandaleone"
maintainer:          "nbrand@mac.com"
copyright:           "2020 Nick Brandaleone"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/nbrandaleone/ses-haskell#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- lens
- conduit
- http-conduit
- resourcet
- text
- async
- aeson
- cryptohash
  #- cryptonite
- blaze-builder
- HTTP
- http-types
- time
- system-locale
  #- old-time
  #- old-locale
- case-insensitive
- base16-bytestring
- byteable

library:
  source-dirs: src

executables:
  am-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ses-haskell

tests:
  am-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ses-haskell
